//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "operation_service")]
pub struct Model {
    pub start_time: DateTimeUtc,
    pub expire_time: DateTimeUtc,
    pub product_id: i64,
    pub resource_setmeal_id: i64,
    pub status: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub is_deleted: bool,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
