//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use std::time::Duration;

use quickcheck::{Arbitrary, Gen};

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "charge_record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub is_deleted: bool,
    pub version: i32,
    pub payment_id: i64,
    pub user_id: i64,
    pub team_id: i64,
    pub amount: i32,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Arbitrary for Model {
    fn arbitrary(g: &mut Gen) -> Model {
        let test_range = (1..100000).into_iter().collect::<Vec<u32>>();
        let status = vec!["pending", "success", "failed"];
        // let t = g.choose(&).unwrap();

        Model {
            id: g.choose(&test_range).unwrap().to_owned() as i64,
            created_at: chrono::NaiveDateTime::from_timestamp(
                g.choose(&test_range).unwrap().to_owned() as i64,
                0,
            ),
            updated_at: chrono::NaiveDateTime::from_timestamp(
                g.choose(&test_range).unwrap().to_owned() as i64,
                0,
            ),
            is_deleted: bool::arbitrary(g),
            version: g.choose(&test_range).unwrap().to_owned() as i32,
            payment_id: g.choose(&test_range).unwrap().to_owned() as i64,
            user_id: g.choose(&test_range).unwrap().to_owned() as i64,
            team_id: g.choose(&test_range).unwrap().to_owned() as i64,
            amount: g.choose(&test_range).unwrap().to_owned() as i32,
            status: g.choose(&status).unwrap().to_string(),
        }
    }
}
