//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "products")]
pub struct Model {
    pub name: String,
    pub resource_setmeal_id: Option<i64>,
    pub r#type: String,
    pub specification: String,
    pub detail: Option<String>,
    pub price: Option<i32>,
    pub month_price: Option<i32>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub is_deleted: bool,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}

use quickcheck::{Arbitrary, Gen};
impl Arbitrary for Model {
    fn arbitrary(g: &mut Gen) -> Model {
        let test_range = (1..100000).into_iter().collect::<Vec<u32>>();
        let status = vec!["pending", "success", "failed"];
        let names = vec![
            "service_name1",
            "product_name2",
            "service_name3",
            "product_name4",
            "service_name5",
            "product_name7",
            "service_name6",
            "product_name8",
        ];
        let sps = vec![
            "GPU * 1 | 16vCPUs | 64GB",
            "GPU * 2 | 1vCPUs | 64GB",
            "GPU * 1 | 64vCPUs | 4GB",
        ];

        Model {
            is_deleted: bool::arbitrary(g),
            version: g.choose(&test_range).unwrap().to_owned() as i32,
            name: g.choose(&names).unwrap().to_string(),
            resource_setmeal_id: Some(g.choose(&test_range).unwrap().to_owned() as i64),
            r#type: g.choose(&status).unwrap().to_string(),
            detail: Some(g.choose(&names).unwrap().to_string()),
            specification: g.choose(&sps).unwrap().to_string(),
            price: Some(g.choose(&test_range).unwrap().to_owned() as i32),
            month_price: Some(g.choose(&test_range).unwrap().to_owned() as i32),
            id: g.choose(&test_range).unwrap().to_owned() as i64,
            created_at: chrono::NaiveDateTime::from_timestamp(
                g.choose(&test_range).unwrap().to_owned() as i64,
                0,
            ),
            updated_at: chrono::NaiveDateTime::from_timestamp(
                g.choose(&test_range).unwrap().to_owned() as i64,
                0,
            ),
        }
    }
}
