//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_status")]
pub enum OrderStatus {
    #[sea_orm(string_value = "not_paid")]
    NotPaid,
    #[sea_orm(string_value = "paid_timeout_cancel")]
    PaidTimeoutCancel,
    #[sea_orm(string_value = "user_cancel")]
    UserCancel,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_type")]
pub enum OrderType {
    #[sea_orm(string_value = "purchase")]
    Purchase,
    #[sea_orm(string_value = "renewal")]
    Renewal,
}
