//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "setemal_price")]
pub struct Model {
    pub r#type: String,
    pub cpu_core: i32,
    pub mem_size: i32,
    pub gpu_core: i32,
    pub storage: Option<i32>,
    pub price_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub is_deleted: bool,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
